name: crawler

on:
  workflow_dispatch:
  repository_dispatch:
    types: Run_Scrapy
#   push:
#     branches:
#       - code
#   schedule:
#     # 定时任务，每晚 22:30 更新数据
#     - cron: '30 22 * * *'
    

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
        
      - name: run crawler
        run: |
          sudo timedatectl set-timezone "Asia/Shanghai"
          cd ./crawler/.code/
          python main.py
      
      - name: add github
        run: |
          git config --global user.email action@github.com
          git config --global user.name GitHub Action
          cd ./crawler/ 
          git add . 
          git commit -m "Github action auto deploy my blog."
          
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
            github_token: ${{ secrets.GITHUB_TOKEN }}
