name: crawler

on:
  push:
    branches:
      - code
  schedule:
    # 定时任务，每晚 22:30 更新数据
    - cron: '30 22 * * *'
    
env:
  DEPLOY_REPO: ${{ github.workspace }}
  DEPLOY_BRANCH: master

jobs:
  build:
    name: Build on python ${{ matrix.python_version }} and ${{ matrix.os }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        os: [ubuntu-latest]
        python_version: [3.x]
        chrome_version: [91.0.4472.19]
      
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      
      - name: Checkout deploy repo
        uses: actions/checkout@v2
        with:
          repository: ${{ env.DEPLOY_REPO }}
          ref: ${{ env.DEPLOY_BRANCH }}
          path: crawler
      
      - name: Setup python ${{ matrix.python_version }}
        uses: actions/setup-python@v2
        with: 
          python-version: ${{ matrix.python_version }}
          architecture: x64
      
      - name: Set pip 
        uses: BSFishy/pip-action@v1
        with:
          requirements: ./crawler/.code/requirements.txt

      - name: Setup chromedriver ${{ matrix.chrome_version }}
        uses: nanasess/setup-chromedriver@master
        with:
          chromedriver-version: ${{ matrix.chrome_version }}
        
      - name: Configuration environment
        run: |
          sudo timedatectl set-timezone "Asia/Shanghai"
          cd ./crawler/.code/
          python main.py
      
      - name: Deploy github
        run: |
          git config --global user.email action@github.com
          git config --global user.name GitHub Action
          cd ./crawler/ 
          git add . 
          git commit -m "Github action auto deploy my blog."
          
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
            github_token: ${{ secrets.GITHUB_TOKEN }}
