name: crawler

on:
  push:
    branches:
      - code
  schedule:
    # 定时任务，每晚 22:30 更新数据
    - cron: '30 22 * * *'
    
env:
  GIT_USER: wonderkun
  GIT_EMAIL: dekunwang2014@gmail.com
  DEPLOY_REPO: wonderkun/crawler
  DEPLOY_BRANCH: code
  THEME_BRANCH: master

jobs:
  build:
    name: Build on python ${{ matrix.python_version }} and ${{ matrix.os }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        os: [ubuntu-latest]
        python_version: [3.x]
        chrome_version: [91.0.4472.19]
      
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      
      - name: Checkout deploy repo
        uses: actions/checkout@v2
        with:
          repository: ${{ env.DEPLOY_REPO }}
          ref: ${{ env.DEPLOY_BRANCH }}
          path: code
      
      - name: Setup python ${{ matrix.python_version }}
        uses: actions/setup-python@v2
        with: 
          python-version: ${{ matrix.python_version }}
          architecture: x64
      
      - name: Set pip 
        uses: BSFishy/pip-action@v1
        with:
          requirements: ./code/.code/requirements.txt

      - name: Setup chromedriver ${{ matrix.chrome_version }}
        uses: nanasess/setup-chromedriver@master
        with:
          chromedriver-version: ${{ matrix.chrome_version }}
        
      - name: Configuration environment
        env:
          HEXO_DEPLOY_PRI: ${{secrets.HEXO_DEPLOY_PRI}}
        run: |
          sudo timedatectl set-timezone "Asia/Shanghai"
          mkdir -p ~/.ssh/
          echo "$HEXO_DEPLOY_PRI" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan github.com >> ~/.ssh/known_hosts
          git config --global user.name $GIT_USER
          git config --global user.email $GIT_EMAIL

      - name: Checkout master repo
        uses: actions/checkout@v2
        with:
          repository: ${{ env.DEPLOY_REPO }}
          ref: ${{ env.THEME_BRANCH }}
          path: master

      - name: Deploy github
        run: |
          cp ./code/.code/main.py ./master/.code/main.py
          cp ./code/www.anquanke.com/all.json ./master/www.anquanke.com/all.json
          cp ./code/xz.aliyun.com/all.json ./master/xz.aliyun.com/all.json
          cd ./master/.code/
          python main.py
          cd ../
          git add . 
          git commit -m "update blog"
          git push git@github.com:wonderkun/crawler.git master:master